### PR TITLE
Fix unauthenticated git protocol no longer supported

### PR DESCRIPTION
**Pull request by sissbruecker**
Currently trying to download a Bower package, for example https://bower-as-a-service.herokuapp.com/download?package=https://github.com/vaadin/vaadin-details&version=1.2.0, returns a `500`with the following error:

> Failed to execute "git ls-remote --tags --heads git://github.com/vaadin/vaadin-details.git", exit code of #128 fatal: remote error: The unauthenticated git protocol on port 9418 is no longer supported. Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information. 

The issue seems to be that Github has finally removed support for the unauthenticated `git://` protocol on March 15, 2022, and that the `bower` NPM package used by `bower-as-a-service` uses that protocol. Fortunately the Bower guys have released a fix here: https://github.com/bower/bower/pull/2612, and released it with version `1.8.14`. Thus just bumping the version of the package resolves this error for bower-as-a-service.

Note that this problem affects [webjars.org](https://www.webjars.org/), where it is currently not possible to release a new webjar version using the Bower GitHub WebJars method. See attached screenshot:

Bildschirmfoto 2022-03-17 um 22 24 29

### CODE REVIEW

**Comment by jamesward** [comment]
Wow! Thank you for this. CI is kicking off and so this should be deployed shortly.  Also I've setup a production alert so that I'll now be notified when the service breaks.

**Comment by sissbruecker** [comment]
Thanks for the prompt response @jamesward , and I see it's already deployed. Awesome 👍

**Comment by jamesward** [comment]
Great! So it works now?

**Comment by sissbruecker** [comment]
Yes, downloading works again ✅

**Pull request merged**
